export const site = {
  siteName:      "Andromeda",
  siteURL:       "andromeda-blog.netlify.app",
  siteEmail1:    "info@andromeda.com",
  siteEmail2:    "",
  siteEmail3:    "",
  siteTel1:      "+380 66 777 88 99",
  siteTel2:      "",
  siteTel3:      "",
  siteGeo:       "https://goo.gl/maps/fgtLEQoDsQjTDTfb7",
  siteFacebook:  "facebook.com/andromeda",
  siteTelegram:  "t.me/andromeda",
  siteAddr1:     "15 Vasilieva,",
  siteAddr2:     "Kamyanets-Podilsky,",
  siteAddr3:     "32300, Ukraine",

  artSlug:       "articles/the-cosmos-awaits",
  artTitle:      "The Cosmos awaits",
  artBanner:     "https://images.ctfassets.net/gioiz80bo502/7LcF0XIMP6LZ3OdMoazA00/220b8f3f5a192676ca8b8364be4b449f/federico-beccari-L8126OwlroY-1920x1080.jpg",
  artAuthor:     "<p>Dr. <strong>Leonard Hofstadter</strong></p><p>senior experimental physicist at the California Institute of Technology</p><p><a href=\"https://bigbangtheory.fandom.com/wiki/Leonard_Hofstadter\">www.wiki.info/Leonard_Hofstadter</a></p>",
};
